// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYC9iLfWABibrE288-_1LjYlLDP0JCho',
    appId: '1:765573917245:web:521b26a5993c4ccd6bd854',
    messagingSenderId: '765573917245',
    projectId: 'wchat-backend',
    authDomain: 'wchat-backend.firebaseapp.com',
    storageBucket: 'wchat-backend.appspot.com',
    measurementId: 'G-Y9P6TXT2GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFtLLreFX59Z1VGZMn1I0bGbI9Mz57c8g',
    appId: '1:765573917245:android:c2ba62443a60c6836bd854',
    messagingSenderId: '765573917245',
    projectId: 'wchat-backend',
    storageBucket: 'wchat-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB98RrAxJ0aSb0rsEg-M-28r7QkQ-WBeu8',
    appId: '1:765573917245:ios:9e67993c1a6d6ac96bd854',
    messagingSenderId: '765573917245',
    projectId: 'wchat-backend',
    storageBucket: 'wchat-backend.appspot.com',
    iosClientId: '765573917245-sg59gu80r7qdjh5jvoknjphq17fkbojm.apps.googleusercontent.com',
    iosBundleId: 'com.example.wchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB98RrAxJ0aSb0rsEg-M-28r7QkQ-WBeu8',
    appId: '1:765573917245:ios:9e67993c1a6d6ac96bd854',
    messagingSenderId: '765573917245',
    projectId: 'wchat-backend',
    storageBucket: 'wchat-backend.appspot.com',
    iosClientId: '765573917245-sg59gu80r7qdjh5jvoknjphq17fkbojm.apps.googleusercontent.com',
    iosBundleId: 'com.example.wchat',
  );
}
